
#Logging Settings
[logging]
	#Enables more logging during recipe registration and syncing.
	recipeRegistration = false
	#Enables more logging for fields handling nearby block updates.
	fieldBlockChanges = false
	#Enables more logging for the recipe matching process.
	recipeMatching = false

#Field Settings
[field]
	#Changes how the field handles a destabilization event (such as a projector breaking mid-craft)
	#Allowed Values: DESTROY_ALL, DESTROY_CATALYST, DESTROY_BLOCKS, RESTORE_ALL, RESTORE_CATALYST, RESTORE_BLOCKS
	destabilizeHandling = "RESTORE_ALL"

