
#General settings on the server
[General]
	#how much extra reach should a player get in creative mode
	#Range: 4.0 ~ 1.7976931348623157E308
	"Creative Reach" = 50.0
	#Which block should be used for salvaging
	"Salvage Block" = "minecraft:smithing_table"

#Settings related level gain
[Levels]
	#The highest level a player can acheive in any skill.
	#NOTE: if this is changing on you to a lower value, that's intentional
	#If your formula makes the required xp to get max level greater than
	#pmmo can store, pmmo will replace your value with the actual max.
	#Range: > 1
	"Max Level" = 329
	#shold levels be determined using an exponential forumula?
	"Use Exponential Formula" = true
	#=====LEAVE -1 VALUE UNLESS YOU WANT STATIC LEVELS=====
	#Replacing the -1 and adding values to this list will set the xp required to advance for each
	#level manually.  Note that the number of level settings you enter into this list
	#will set your max level.  If you only add 10 entries, your max level will be 10.
	#This setting is intended for players/ops who want fine-tune control over their
	#level growth.  use with caution.  
	#
	#As a technical note, if you enter values that are not greater than their previous
	#value, the entire list will be ignored and revert back to the selected exponential
	#or linear formulaic calculation
	Static_Levels = [-1]
	#How much experience should players lose when they die?
	#zero is no loss, one is lose everything
	#Range: 0.0 ~ 1.0
	"Loss on death" = 0.05
	#should loss of experience cross levels?
	#for example, if true, a player with 1 xp above their current level would lose the
	#[Loss on death] percentage of xp and fall below their current level.  However,
	#if false, the player would lose only 1 xp as that would put them at the base xp of their current level
	"Lose Levels On Death" = false
	#This setting only matters if [Lose Level On Death] is set to false.
	#If this is true the [Loss On Death] applies only to the experience above the current level
	#for example if level 3 is 1000k xp and the player has 1020 and dies.  the player will only lose
	#the [Loss On Death] of the 20 xp above the level's base.
	"Lose Only Excess" = true
	#Modifies how much xp is earned.  This is multiplicative to the XP.
	"Global Modifier" = 1.0

	#Modifies xp gains for specific skills.  This is multiplicative to the XP.
	[Levels."Skill Modifiers"]
		agility = 1.0

	#Settings for Linear XP configuration
	[Levels."LINEAR LEVELS"]
		#what is the base xp to reach level 2 (this + level * xpPerLevel)
		#Range: 0 ~ 9223372036854775807
		"Base XP" = 250
		#What is the xp increase per level (baseXp + level * this)
		#Range: 0.0 ~ 1.7976931348623157E308
		"Per Level" = 500.0

	#Settings for Exponential XP configuration
	[Levels."EXPONENTIAL LEVELS"]
		#What is the x in: x * ([Power Base]^([Per Level] * level))
		#Range: > 1
		"Base XP" = 250
		#What is the x in: [Base XP] * (x^([Per Level] * level))
		#Range: 0.0 ~ 1.7976931348623157E308
		"Power Base" = 1.104088404342588
		#What is the x in: [Base XP] * ([Power Base]^(x * level))
		#Range: 0.0 ~ 1.7976931348623157E308
		"Per Level" = 1.1

#Should requirements apply for the applicable action type
[Requirements]
	"WEAR Req Enabled" = true
	"USE_ENCHANTMENT Req Enabled" = true
	"TOOL Req Enabled" = true
	"WEAPON Req Enabled" = true
	"USE Req Enabled" = true
	"PLACE Req Enabled" = true
	"BREAK Req Enabled" = true
	"KILL Req Enabled" = true
	"TRAVEL Req Enabled" = true
	"RIDE Req Enabled" = true
	"TAME Req Enabled" = true
	"BREED Req Enabled" = true
	"INTERACT Req Enabled" = true
	"ENTITY_INTERACT Req Enabled" = true

#All settings related to the gain of experience
[XP_Gains]
	#how much of the original XP should be awarded when a player breaks a block they placed
	#Range: 0.0 ~ 1.7976931348623157E308
	"Reuse Penalty" = 0.0
	#Should xp Gains from perks be added onto by configured xp values
	"Perks Plus Configs" = false

	#Settings related to certain default event XP awards.
	[XP_Gains.Event_XP_Specifics]

		[XP_Gains.Event_XP_Specifics.Damage_Received]

			[XP_Gains.Event_XP_Specifics.Damage_Received."FROM_ENVIRONMENT Skills and Ratios"]
				endurance = 10.0

			[XP_Gains.Event_XP_Specifics.Damage_Received."FROM_IMPACT Skills and Ratios"]
				endurance = 15.0

			[XP_Gains.Event_XP_Specifics.Damage_Received."FROM_MAGIC Skills and Ratios"]
				magic = 15.0

			[XP_Gains.Event_XP_Specifics.Damage_Received."FROM_PROJECTILE Skills and Ratios"]
				endurance = 15.0

			[XP_Gains.Event_XP_Specifics.Damage_Received."RECEIVE_DAMAGE Skills and Ratios"]
				endurance = 1.0

		[XP_Gains.Event_XP_Specifics.Damage_Dealt]

			[XP_Gains.Event_XP_Specifics.Damage_Dealt."DEAL_MELEE_DAMAGE Skills and Ratios"]
				combat = 1.0

			[XP_Gains.Event_XP_Specifics.Damage_Dealt."DEAL_RANGED_DAMAGE SKills and Ratios"]
				archery = 1.0

		[XP_Gains.Event_XP_Specifics.Jumps]

			[XP_Gains.Event_XP_Specifics.Jumps."JUMP Skills and Ratios"]
				agility = 2.5

			[XP_Gains.Event_XP_Specifics.Jumps."SPRINT_JUMP Skills and Ratios"]
				agility = 2.5

			[XP_Gains.Event_XP_Specifics.Jumps."CROUCH_JUMP Skills and Ratios"]
				agility = 2.5

		[XP_Gains.Event_XP_Specifics.Player_Actions]

			[XP_Gains.Event_XP_Specifics.Player_Actions."BREATH_CHANGE Skills and Ratios"]
				swimming = 1.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."HEALTH_CHANGE Skills and Ratios"]
				endurance = 1.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."SPRINTING Skills and Ratios"]
				agility = 100.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."SUBMERGED Skills and Ratios"]
				swimming = 1.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."SWIMMING Skills and Ratios"]
				swimming = 100.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."DIVING Skills and Ratios"]
				swimming = 150.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."SURFACING Skills and Ratios"]
				swimming = 50.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."SWIM_SPRINTING Skills and Ratios"]
				swimming = 200.0

#All setings governing party behavior
[Party]
	#How close do party members have to be to share experience.
	#Range: > 0
	"Party Range" = 50
	#How much bonus xp should parties earn.
	#This value is multiplied by the party size.
	#Range: 1.0 ~ 1.7976931348623157E308
	"Party Bonus" = 1.05

#settings related to how strong mobs get based on player level.
[Mob_Scaling]
	#Should mob scaling be turned on.
	"Enable Mob Scaling" = true
	#How far should players be from spawning mobs to affect scaling?
	#Range: > 0
	"Scaling AOE" = 50
	#what is the minimum level for scaling to kick in
	#Range: > 0
	"Base Level" = 0

	#How should mob attributes be calculated with respect to the player's level.
	[Mob_Scaling.Formula]
		#shold levels be determined using an exponential forumula?
		"Use Exponential Formula" = true

		#Settings for Linear scaling configuration
		[Mob_Scaling.Formula.LINEAR_LEVELS]
			#What is the xp increase per level ((level - base_level) * this)
			#Range: 0.0 ~ 1.7976931348623157E308
			"Per Level" = 1.0

		#Settings for Exponential scaling configuration
		[Mob_Scaling.Formula.EXPONENTIAL_LEVELS]
			#What is the x in: (x^([Per Level] * level))
			#Range: 0.0 ~ 1.7976931348623157E308
			"Power Base" = 1.104088404342588
			#What is the x in: ([Power Base]^(x * level))
			#Range: 0.0 ~ 1.7976931348623157E308
			"Per Level" = 1.0

	#These settings control which skills affect scaling and the ratio for each skill
	#HP Scale: 1 = half a heart, or 1 hitpoint
	#SPD Scale: 0.7 is base for most mobs.  this is added to that. so 0.7 from scaling is double speed
	#DMG Scale: is a multiplier of their base damage.  1 = no change, 2 = double damage
	#negative values are possible and you can use this to create counterbalance skills
	[Mob_Scaling.Scaling_Settings]

		[Mob_Scaling.Scaling_Settings."HP Scaling and Ratios"]
			combat = 0.01

		[Mob_Scaling.Scaling_Settings."Speed Scaling and Ratios"]
			combat = 0.001

		[Mob_Scaling.Scaling_Settings."Damage Scaling and Ratios"]
			combat = 0.001

#Settings related to the Vein Miner
[Vein_Miner]
	#setting to false disables all vein features
	"vein enabled" = true
	#If true, default consume will be ignored in favor of only allowing
	#veining blocks with declared values.
	"Require Settings" = false
	#how much a block should consume if no setting is defined.
	"Vein Mine Default Consume" = 1

