
#========================================================================
#
# All skills in pmmo are defined when they are used anywhere in PMMO.
# You do not need to define a skill here to use it. However, defining
# a skills attributes here will give you amore rounded skill list and
# a cleaner looking mod. Note that all the defaults here can be replaced
# if you wish. Also note that when using custom icon sizes they must be
# a square image(eg. 16x16, 24x24, 32x32) and they default to 18x18.
#
#========================================================================
[Skills]

	[Skills.Entry]

		[Skills.Entry.magic]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 255
			icon = "minecraft:textures/particle/enchanted_hit.png"
			iconSize = 8
			noAfkPenalty = false

		[Skills.Entry.slayer]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16777215
			icon = "minecraft:textures/item/netherite_sword.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.fishing]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 52479
			icon = "minecraft:textures/item/fishing_rod.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.fightgroup]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16777215
			icon = "pmmo:textures/skills/missing_icon.png"
			iconSize = 18
			noAfkPenalty = false

			[Skills.Entry.fightgroup.groupFor]
				combat = 0.5
				endurance = 0.3
				archery = 0.2

		[Skills.Entry.combat]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16724736
			icon = "minecraft:textures/mob_effect/strength.png"
			iconSize = 18
			noAfkPenalty = false

		[Skills.Entry.alchemy]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 15112448
			icon = "minecraft:textures/item/potion.png"
			iconSize = 16
			noAfkPenalty = true

		[Skills.Entry.mining]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 65535
			icon = "minecraft:textures/mob_effect/haste.png"
			iconSize = 18
			noAfkPenalty = false

		[Skills.Entry.engineering]
			maxLevel = 100
			displayGroupName = false
			useTotalLevels = false
			color = 16777215
			icon = "minecraft:textures/item/redstone.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.endurance]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 13369344
			icon = "minecraft:textures/mob_effect/absorption.png"
			iconSize = 18
			noAfkPenalty = false

		[Skills.Entry.building]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 65535
			icon = "pmmo:textures/skills/building.png"
			iconSize = 32
			noAfkPenalty = false

		[Skills.Entry.smithing]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 15790320
			icon = "pmmo:textures/skills/smithing.png"
			iconSize = 32
			noAfkPenalty = true

		[Skills.Entry.swimming]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 3368703
			icon = "minecraft:textures/mob_effect/dolphins_grace.png"
			iconSize = 18
			noAfkPenalty = false

		[Skills.Entry.woodcutting]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16753434
			icon = "minecraft:textures/item/iron_axe.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.gunslinging]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 13877667
			icon = "pmmo:textures/skills/missing_icon.png"
			iconSize = 18
			noAfkPenalty = false

		[Skills.Entry.crafting]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16750848
			icon = "pmmo:textures/skills/crafting.png"
			iconSize = 32
			noAfkPenalty = false

		[Skills.Entry.excavation]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 15112448
			icon = "minecraft:textures/item/iron_shovel.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.farming]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 58880
			icon = "minecraft:textures/item/wheat.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.flying]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 13421823
			icon = "minecraft:textures/item/elytra.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.cooking]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 15112448
			icon = "minecraft:textures/item/cooked_mutton.png"
			iconSize = 16
			noAfkPenalty = true

		[Skills.Entry.agility]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 6736998
			icon = "minecraft:textures/mob_effect/speed.png"
			iconSize = 18
			noAfkPenalty = false

		[Skills.Entry.sailing]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 10073087
			icon = "minecraft:textures/item/oak_boat.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.hunter]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 13596693
			icon = "minecraft:textures/item/diamond_sword"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.archery]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16776960
			icon = "minecraft:textures/item/bow.png"
			iconSize = 16
			noAfkPenalty = false

		[Skills.Entry.taming]
			maxLevel = 2147483647
			displayGroupName = false
			useTotalLevels = false
			color = 16777215
			icon = "minecraft:textures/item/leash"
			iconSize = 16
			noAfkPenalty = false

