
[voice_chat]
	#The port of the voice chat server
	#Setting this to "-1" sets the port to the Minecraft servers port
	#Range: -1 ~ 65535
	port = 24454
	#The IP address to bind the voice chat server on
	#Leave empty to bind to an IP address chosen by the kernel
	bind_address = ""
	#The distance to where the voice can be heard
	#Range: 1.0 ~ 1000000.0
	max_voice_distance = 48.0
	#The multiplier the voice distance will be reduced by when sneaking
	#Range: 0.01 ~ 1.0
	crouch_distance_multiplier = 1.0
	#The multiplier the voice distance will be reduced by when whispering
	#Range: 0.01 ~ 1.0
	whisper_distance_multiplier = 0.5
	#The opus codec
	#Allowed Values: VOIP, AUDIO, RESTRICTED_LOWDELAY
	codec = "VOIP"
	#The maximum size in bytes in a voice packet
	#Set this to a lower value if your voice packets don't arrive
	#Range: 256 ~ 10000
	mtu_size = 1024
	#The frequency in which keep alive packets are sent
	#Setting this to a higher value may result in timeouts
	#Range: > 1000
	keep_alive = 1000
	#If group chats are allowed
	enable_groups = true
	#If players in group chats can be heard locally
	open_groups = false
	#The host name that clients should use to connect to the voice chat
	#Don't change this value if you don't know what you are doing
	voice_host = ""
	#If players are allowed to record the voice chat
	allow_recording = true
	#If spectators are allowed to talk to other players
	spectator_interaction = false
	#If spectators can talk to players they are spectating
	spectator_player_possession = false
	#If players without the mod should get kicked from the server
	force_voice_chat = false
	#The amount of milliseconds, the server should wait to check if the player has the mod installed
	#Only active when force_voice_chat is set to true
	#Range: > 100
	login_timeout = 10000
	#The range where the voice chat should broadcast audio to
	#A value <0 means 'max_voice_distance'
	#Range: -1.0 ~ 1.7976931348623157E308
	broadcast_range = -1.0

