
[items]
	oxygen_can_fluid_capacity = 500
	oxygen_can_fluid_transfer = 125
	netherite_oxygen_can_fluid_capacity = 1000
	netherite_oxygen_can_fluid_transfer = 250

[machines]
	fuel_loader_fluid_capacity = 8000
	fuel_loader_fluid_transfer = 250
	#Blocks from Fuel Loader to each direction
	fuel_loader_working_range = 2
	automation_nasa_workbench_energy_capacity = 9600
	automation_nasa_workbench_energy_usage = 24
	automation_nasa_workbench_cook_time = 200
	gravity_normalizer_energy_capacity = 9600
	#Blocks = x * y * z
	gravity_normalizer_energy_per_blocks = 0.5
	gravity_normalizer_max_length = 31
	gravity_normalizer_proof_duration = 10

[enchantments]
	#Show tooltip on this mod's enchanted book
	tooltip_enabled = true
	#Tooltip will don't show when 'Enchantment Descriptions' or 'Enchantment Lore' or 'CoFH Core' installed.
	#but, if this set 'true' show tooltip with ignore that mods.
	tooltip_ignore = false
	#Energy usage for breath [in every 30 ticks]
	space_breathing_energy_using = 30
	#Oxygen usage on using durability
	space_breathing_durability_oxygen = 2
	#Durability usage for breath
	space_breathing_durability_using = 1
	#Breath duration on using durability [ticks, be multiple of 30]
	space_breathing_durability_duration = 60
	#Energy usage for proof [in every 10 ticks]
	space_fire_proof_energy_using = 10
	#Durability usage for proof
	space_fire_proof_durability_using = 1
	#Proof duration on using durability [ticks, be multiple of 10]
	space_fire_proof_durability_duration = 60
	#Energy usage for proof [in every 10 ticks]
	acid_rain_proof_energy_using = 10
	#Durability usage for proof
	acid_rain_proof_durability_using = 1
	#Proof duration on using durability [ticks, be multiple of 10]
	acid_rain_proof_durability_duration = 60
	#Energy usage for proof [in every 10 ticks]
	gravity_normalizing_energy_using = 10
	#Durability usage for proof
	gravity_normalizing_durability_using = 1
	#Proof duration on using durability [ticks, be multiple of 10]
	gravity_normalizing_durability_duration = 60

[compats]

	[compats.mekanism]
		#Energy usage for provide oxygen [in every 30 ticks]
		modules_space_breathing_energy_using_provide = 300
		#Energy usage per mb when produce Mekanism oxygen to player in water, rain
		modules_space_breathing_energy_using_produce = 200
		#Energy usage for proof in every ticks [in every 10 ticks]
		modules_space_fire_proof_energy_using = 100
		#Energy usage for proof in every ticks [in every 10 ticks]
		modules_acid_rain_proof_energy_using = 100
		#Energy usage for proof in every ticks [in every 10 ticks]
		modules_gravity_normalizing_energy_using = 100

	[compats.pneumaticcraft]
		#Air usage for provide oxygen [in every 30 ticks]
		upgades_space_breathing_air_using = 150
		#Air usage for proof [in every 10 ticks]
		upgades_space_fire_proof_air_using = 50
		#Air usage for proof [in every 10 ticks]
		upgades_acid_rain_proof_air_using = 50
		#Air usage for proof [in every 10 ticks]
		upgades_gravity_normalizing_air_using = 50

