
#Chemical Liquifier
[liquifier]
	#Fluid capacity in Liquifier tank.
	#Default: 16000 (16 buckets)
	#Range: > 1
	fluidCapacity = 16000
	#Energy consumed per tick when Liquifier is processing
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 50
	#Ticks per operation when using the Liquifier.
	#Default: 100 ticks
	#Range: > 1
	ticksPerOperation = 100
	#Maximum energy capacity for the Liquifier.
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

#Fusion
[fusion]
	#Energy consumed per tick when the Fusion multiblock is processing
	#Default: 300 FE
	#Range: > 0
	energyPerTick = 300
	#Ticks per operation when using the Fusion multiblock
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Maximum energy capacity of the Fusion multiblock
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

#Chemical Compactor
[compactor]
	#Energy consumed per tick when Compactor is processing.
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 50
	#Ticks per operation when using the Compactor.
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Maximum energy capacity for the Compactor.
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

#Fission
[fission]
	#Energy consumed per tick when the Fission multiblock is processing.
	#Default: 300 FE
	#Range: > 0
	energyPerTick = 300
	#Ticks per operation when using the Fission multiblock
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Maximum energy capacity of the Fission multiblock.
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

#Chemical Combiner
[combiner]
	#Energy consumed per tick when Combiner is processing.
	#Default: 200 FE
	#Range: > 0
	energyPerTick = 200
	#Ticks per operation when using the Combiner.
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Maximum energy capacity for the Combiner.
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

#Chemical Dissolver
[dissolver]
	#Energy consumed per tick when Dissolver is processing.
	#Default: 100 FE
	#Range: > 0
	energyPerTick = 100
	#Ticks per operation when using the Dissolver.
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Maximum energy capacity for the Dissolver.
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

#Chemical Atomizer
[atomizer]
	#Fluid capacity in Atomizer tank.
	#Default: 16000 (16 buckets)
	#Range: > 1
	fluidCapacity = 16000
	#Energy consumed per tick when Atomizer is processing.
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 50
	#Ticks per operation when using the Atomizer.
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Maximum energy capacity for the Atomizer.
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000

