
[spawncontrol]

	[spawncontrol.overworld]
		#Enable Aluminum Worldgen(Overworld)
		aluminum = false
		#Enable Iridium Worldgen(Overworld)
		iridium = false
		#Enable Lead Worldgen(Overworld)
		lead = false
		#Enable Nickel Worldgen(Overworld)
		nickel = false
		#Enable Osmium Worldgen(Overworld)
		osmium = false
		#Enable Platinum Worldgen(Overworld)
		platinum = false
		#Enable Silver Worldgen(Overworld)
		silver = false
		#Enable Tin Worldgen(Overworld)
		tin = false
		#Enable Uranium Worldgen(Overworld)
		uranium = false
		#Enable Zinc Worldgen(Overworld)
		zinc = false
		#Enable Ruby Worldgen(Overworld-Plains)
		ruby = false
		#Enable Sapphire Worldgen(Overworld-Ocean)
		sapphire = false
		#Enable Peridot Worldgen(Overworld-Desert)
		peridot = false

	[spawncontrol.nether]
		#Enable Aluminum Worldgen(Nether)
		aluminum_nether = false
		#Enable Iridium Worldgen(Nether)
		iridium_nether = false
		#Enable Lead Worldgen(Nether)
		lead_nether = false
		#Enable Nickel Worldgen(Nether)
		nickel_nether = false
		#Enable Osmium Worldgen(Nether)
		osmium_nether = false
		#Enable Platinum Worldgen(Nether)
		platinum_nether = false
		#Enable Silver Worldgen(Nether)
		silver_nether = false
		#Enable Tin Worldgen(Nether)
		tin_nether = false
		#Enable Uranium Worldgen(Nether)
		uranium_nether = false
		#Enable Zinc Worldgen(Nether)
		zinc_nether = false

	[spawncontrol.end]
		#Enable Aluminum Worldgen(The End)
		aluminum_end = false
		#Enable Iridium Worldgen(The End)
		iridium_end = false
		#Enable Lead Worldgen(The End)
		lead_end = false
		#Enable Nickel Worldgen(The End)
		nickel_end = false
		#Enable Osmium Worldgen(The End)
		osmium_end = false
		#Enable Platinum Worldgen(The End)
		platinum_end = false
		#Enable Silver Worldgen(The End)
		silver_end = false
		#Enable Tin Worldgen(The End)
		tin_end = false
		#Enable Uranium Worldgen(The End)
		uranium_end = false
		#Enable Zinc Worldgen(The End)
		zinc_end = false

[spawntuning]

	[spawntuning.aluminum]
		#Aluminum generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		aluminum_min_y = 50
		#Aluminum generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		aluminum_max_y = 120
		#Aluminum deposit size(number of ores)
		#Range: 1 ~ 64
		aluminum_deposit_size = 7
		#Aluminum deposit count(number of veins)
		#Range: 1 ~ 64
		aluminum_deposit_count = 20

	[spawntuning.iridium]
		#Iridium generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		iridium_min_y = 5
		#Iridium generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		iridium_max_y = 69
		#Iridium deposit size(number of ores)
		#Range: 1 ~ 64
		iridium_deposit_size = 2
		#Iridium rarity, lower = more common
		#Range: 1 ~ 64
		iridium_deposit_count = 1

	[spawntuning.zinc]
		#Zinc generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		zinc_min_y = 5
		#Zinc generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		zinc_max_y = 100
		#Zinc deposit size(number of ores)
		#Range: 1 ~ 64
		zinc_deposit_size = 7
		#Zinc deposit count(number of veins)
		#Range: 1 ~ 64
		zinc_deposit_count = 20

	[spawntuning.lead]
		#Lead generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		lead_min_y = 5
		#Lead generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		lead_max_y = 95
		#Lead deposit size(number of ores)
		#Range: 1 ~ 64
		lead_deposit_size = 7
		#Lead deposit count(number of veins)
		#Range: 1 ~ 64
		lead_deposit_count = 20

	[spawntuning.nickel]
		#Nickel generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		nickel_min_y = 1
		#Nickel generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		nickel_max_y = 85
		#Nickel deposit size(number of ores)
		#Range: 1 ~ 64
		nickel_deposit_size = 7
		#Nickel deposit count(number of veins)
		#Range: 1 ~ 64
		nickel_deposit_count = 20

	[spawntuning.osmium]
		#Osmium generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		osmium_min_y = 10
		#Osmium generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		osmium_max_y = 100
		#Osmium deposit size(number of ores)
		#Range: 1 ~ 64
		osmium_deposit_size = 7
		#Osmium deposit count(number of veins)
		#Range: 1 ~ 64
		osmium_deposit_count = 20

	[spawntuning.platinum]
		#Platinum generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		platinum_min_y = 1
		#Platinum generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		platinum_max_y = 70
		#Platinum deposit size(number of ores)
		#Range: 1 ~ 64
		platinum_deposit_size = 3
		#Platinum deposit count(number of veins)
		#Range: 1 ~ 64
		platinum_deposit_count = 20

	[spawntuning.silver]
		#Silver generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		silver_min_y = 50
		#Silver generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		silver_max_y = 120
		#Silver deposit size(number of ores)
		#Range: 1 ~ 64
		silver_deposit_size = 5
		#Silver deposit count(number of veins)
		#Range: 1 ~ 64
		silver_deposit_count = 20

	[spawntuning.tin]
		#Tin generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		tin_min_y = 55
		#Tin generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		tin_max_y = 180
		#Tin deposit size(number of ores)
		#Range: 1 ~ 64
		tin_deposit_size = 7
		#Tin deposit count(number of veins)
		#Range: 1 ~ 64
		tin_deposit_count = 20

	[spawntuning.ruby]
		#Ruby generates no lower than
		#Range: -64 ~ 320
		ruby_min_y = -62
		#Ruby generates no higher than
		#Range: -64 ~ 320
		ruby_max_y = 16
		#Ruby deposit size(number of ores)
		#Range: 1 ~ 64
		ruby_deposit_size = 2
		#Ruby deposit count(number of veins)
		#Range: 1 ~ 64
		ruby_deposit_count = 3

	[spawntuning.sapphire]
		#Sapphire generates no lower than
		#Range: -64 ~ 320
		sapphire_min_y = -62
		#Sapphire generates no higher than
		#Range: -64 ~ 320
		sapphire_max_y = 16
		#Sapphire deposit size(number of ores)
		#Range: 1 ~ 64
		sapphire_deposit_size = 2
		#Sapphire deposit count(number of veins)
		#Range: 1 ~ 64
		sapphire_deposit_count = 3

	[spawntuning.peridot]
		#Peridot generates no lower than
		#Range: -64 ~ 320
		peridot_min_y = -62
		#Peridot generates no higher than
		#Range: -64 ~ 320
		peridot_max_y = 16
		#Peridot deposit size(number of ores)
		#Range: 1 ~ 64
		peridot_deposit_size = 2
		#Peridot deposit count(number of veins)
		#Range: 1 ~ 64
		peridot_deposit_count = 3

	[spawntuning.uranium]
		#Uranium generates no lower than X blocks above world BOTTOM
		#Range: -64 ~ 320
		uranium_min_y = 1
		#Uranium generates no higher than X blocks above world BOTTOM
		#Range: 0 ~ 320
		uranium_max_y = 70
		#Uranium deposit size(number of ores)
		#Range: 1 ~ 64
		uranium_deposit_size = 4
		#Uranium deposit count(number of veins)
		#Range: 1 ~ 64
		uranium_deposit_count = 20

