#Range: 1 ~ 4
itemsPerColumn = 4
#Range: 1 ~ 4
itemsPerRow = 4
diyData = true
showDevData = true
enchantsBlacklist = ["flimflam", "soulBound"]
hiddenTabs = []
dimensionsBlacklist = [-11]
disableLootManagerReloading = true

