
#Jer Integration override options
[jer-integration]
	#Enable / Disable patch for Applied Energistics 2
	ae2 = true
	#Enable / Disable patch for Create
	create = true
	#Enable / Disable patch for Immersive Engineering
	immersiveengineering = true
	#Enable / Disable patch for Tinkers' Construct
	tconstruct = true
	#Enable / Disable patch for Mekanism
	mekanism = true

