
#Performance Settings
[performance]
	#When should the information be displayed in the overlay? 0 = no, 1 = always, 2 = only in extended or debug, 3 = when you have a wrench in your hand, 4 = when you have any component in your hand
	#Range: 0 ~ 4
	display_mode = 1

