
[general]
	#Whether blocks with block entities can be placed in Framed Blocks
	allowBlockEntities = false
	#Enables the intangbility feature. Disabling this also prevents moving through blocks that are already marked as intangible
	enableIntangibleFeature = false
	#The item to use for making Framed Blocks intangible. The value must be a valid item registry name
	intangibleMarkerItem = "minecraft:phantom_membrane"

